package constants;

import java.util.ArrayList;
import java.util.HashMap;

public class Constants {

	public static String URL = "jdbc:postgresql://localhost:5432/stocks";
	public static String USERNAME = "postgres";
	public static String PASSWORD = "graham23";
	
	public static enum BAR_SIZE {BAR_15S, BAR_30S, BAR_1M, BAR_3M, BAR_5M, BAR_10M, BAR_15M, BAR_30M, BAR_1H, BAR_2H, BAR_4H, BAR_6H, BAR_8H, BAR_12H, BAR_1D};
	
	public static String BAR_TABLE = "bar";			
	public static String METRICS_TABLE = "metrics";	
	public static String INDEXLIST_TABLE = "indexlist"; // NYSE, Nasdaq, ETF, Index, Bitcoin
	public static String SECTORANDINDUSTRY_TABLE = "sectorandindustry";
	public static String REALTIMESYMBOLS_TABLE = "realtimesymbols";

	public static int NUM_BARS_NEEDED_FOR_REALTIME_DOWNLOAD_METRIC_CALC = 101;
	
	// Datasource URLs.  These occasionally break and need to be fixed or replaced.
	public static String YAHOO_NYSE_SYMBOL_URL = "http://finance.yahoo.com/q/cp?s=%5ENYA&c="; // "c" parameter = a page number (0+) // Broken as of 7/2/2015
	public static String NYSE_SYMBOL_URL = "http://www1.nyse.com/indexes/nyaindex.csv";
	public static String YAHOO_NASDAQ_SYMBOL_URL = "http://finance.yahoo.com/q/cp?s=%5EIXIC&c=";
	public static String YAHOO_DJIA_SYMBOL_URL = "http://finance.yahoo.com/q/cp?s=%5EDJI&c=";
	public static String YAHOO_ETF_SYMBOL_URL = "http://finance.yahoo.com/etf/lists/?mod_id=mediaquotesetf&tab=tab3&scol=volint&stype=desc&rcnt=100"; 
	public static String WIKI_ETF_SYMBOL_URL = "http://en.wikipedia.org/wiki/List_of_American_exchange-traded_funds";
	public static String YAHOO_REALTIME_QUOTE_URL = "http://download.finance.yahoo.com/d/quotes.csv?f=sk1d1c6ohgv&e=.csv&s=";
	public static String WIKI_SP500_SYMBOL_URL = "http://en.wikipedia.org/wiki/List_of_S%26P_500_companies"; // Broken as of 7/2/2015
	public static String OKFN_SP500_SYMBOL_URL = "http://data.okfn.org/data/core/s-and-p-500-companies/r/constituents.csv";
	public static String BITCOINCHARTS_CSV_URL = "http://api.bitcoincharts.com/v1/csv/";
	
	public static String OTHER_SELL_METRIC_NUM_BARS_LATER = "# Bars";
	public static String OTHER_SELL_METRIC_PERCENT_UP = "% Up";
	public static String OTHER_SELL_METRIC_PERCENT_DOWN = "% Down";
	
	public static String STOP_METRIC_NONE = "None";
	public static String STOP_METRIC_PERCENT_DOWN = "% Down";
	public static String STOP_METRIC_PERCENT_UP = "% Up";
	public static String STOP_METRIC_NUM_BARS = "# Bars";

	public static ArrayList<String> METRICS = new ArrayList<String>();
	public static ArrayList<String> METRICS_NB = new ArrayList<String>(); // These tend to be low info gain ones in attribute selection
	public static ArrayList<String> METRICS_RF = new ArrayList<String>(); // These tend to be the high info gain ones in attribute selection
	public static ArrayList<String> OTHER_SELL_METRICS = new ArrayList<String>();
	public static ArrayList<String> STOP_METRICS = new ArrayList<String>();
	public static HashMap<String, Integer> METRIC_NEEDED_BARS = new HashMap<String, Integer>();
	
	static {
		// METRICS
//		METRICS.add("aroonoscillator10");  
//		METRICS.add("aroonoscillator25"); 
//		METRICS.add("aroonoscillator50"); 
//		METRICS.add("atr10"); 
//		METRICS.add("atr20"); 
//		METRICS.add("atr40"); 
//		METRICS.add("atr60");
//		METRICS.add("breakout20"); 
//		METRICS.add("breakout50"); 
//		METRICS.add("breakout100"); 
//		METRICS.add("breakout200");
//		METRICS.add("cci5"); 
//		METRICS.add("cci10"); 
//		METRICS.add("cci20"); 
//		METRICS.add("cci40"); 
//		METRICS.add("cci60"); 
//		METRICS.add("consecutiveups"); 
//		METRICS.add("consecutivedowns");
//		METRICS.add("cps");
		METRICS.add("dvol5ema");
//		METRICS.add("dvol10ema"); 
//		METRICS.add("dvol25ema");
//		METRICS.add("dvol50ema");
//		METRICS.add("dvol75ema");
//		METRICS.add("gapboll10");
//		METRICS.add("gapboll20");
//		METRICS.add("gapboll50");
//		METRICS.add("intradayboll10");
//		METRICS.add("intradayboll20");
//		METRICS.add("intradayboll50");
		METRICS.add("macd6_13_5");
//		METRICS.add("macd12_26_9");
//		METRICS.add("macd20_40_9"); 
		METRICS.add("macdsignal6_13_5");
//		METRICS.add("macdsignal12_26_9");
//		METRICS.add("macdsignal20_40_9"); 
		METRICS.add("macdhistory6_13_5");
//		METRICS.add("macdhistory12_26_9");
//		METRICS.add("macdhistory20_40_9"); 
//		METRICS.add("mfi4"); 
//		METRICS.add("mfi8"); 
//		METRICS.add("mfi12");
//		METRICS.add("mfi16"); 
		METRICS.add("mfi30"); 
		METRICS.add("mfi60"); 
//		METRICS.add("mvol10");
//		METRICS.add("mvol20");
//		METRICS.add("mvol50");
//		METRICS.add("mvol100"); 
//		METRICS.add("mvol200");
//		METRICS.add("pricebolls10");
//		METRICS.add("pricebolls20");
//		METRICS.add("pricebolls50");
//		METRICS.add("pricebolls100");
//		METRICS.add("pricebolls200");
//		METRICS.add("psar");
//		METRICS.add("rsi2");
//		METRICS.add("rsi5");
//		METRICS.add("rsi10"); 
//		METRICS.add("rsi14"); 
		METRICS.add("rsi25"); 
//		METRICS.add("rsi40");
//		METRICS.add("stochasticdrsi9_2_2"); 
//		METRICS.add("stochasticdrsi14_3_3"); 
//		METRICS.add("stochasticdrsi20_5_5"); 
//		METRICS.add("stochastick9_2_2"); 
//		METRICS.add("stochasticd9_2_2");  
//		METRICS.add("stochastick14_3_3"); 
//		METRICS.add("stochasticd14_3_3");  
//		METRICS.add("stochastick20_5_5");
//		METRICS.add("stochasticd20_5_5"); 
//		METRICS.add("tsf10");
//		METRICS.add("tsf20"); 
//		METRICS.add("tsf30"); 
//		METRICS.add("tsf40"); 
//		METRICS.add("tsf60");
//		METRICS.add("ultimateoscillator4_10_25"); 
//		METRICS.add("ultimateoscillator8_20_50");
		METRICS.add("ultimateoscillator16_40_100");
//		METRICS.add("volumebolls10");
//		METRICS.add("volumebolls20");
//		METRICS.add("volumebolls50");
//		METRICS.add("volumebolls100");
//		METRICS.add("volumebolls200");
//		METRICS.add("williamsr10");  
//		METRICS.add("williamsr20");  
//		METRICS.add("williamsr50"); 
//		METRICS.add("cdlhammer");
//		METRICS.add("cdldoji");
//		METRICS.add("cdlmorningstar");
		METRICS.add("timerange.05");
		METRICS.add("timerange.1");
		METRICS.add("timerange.2");
		METRICS.add("timerange.3");
		METRICS.add("timerange.5");
		METRICS.add("rangepressure50");
		METRICS.add("rangepressure100");
		METRICS.add("rangepressure200");
		
		// METRICS_RF uses close but not hour - These seem to be high info gain
		METRICS_RF.add("rsi10");
		METRICS_RF.add("rsi14"); 
		METRICS_RF.add("rsi40"); 
		METRICS_RF.add("cps");
		METRICS_RF.add("pricebolls50");
		METRICS_RF.add("pricebolls100");
		METRICS_RF.add("pricebolls200");
		METRICS_RF.add("volumebolls50");
		METRICS_RF.add("volumebolls100");
		METRICS_RF.add("volumebolls200");
		METRICS_RF.add("dvol10ema");
		METRICS_RF.add("breakout20"); 
		METRICS_RF.add("breakout50"); 
		METRICS_RF.add("breakout100"); 
		METRICS_RF.add("williamsr50");
		METRICS_RF.add("macd12_26_9");
		METRICS_RF.add("macd20_40_9"); 
		METRICS_RF.add("macdsignal12_26_9");
		METRICS_RF.add("macdsignal20_40_9"); 
		METRICS_RF.add("macdhistory12_26_9");
		METRICS_RF.add("macdhistory20_40_9"); 
		METRICS_RF.add("tsf10");
		METRICS_RF.add("tsf20"); 
		METRICS_RF.add("tsf30"); 
		METRICS_RF.add("tsf40");
		METRICS_RF.add("tsf60"); 
		METRICS_RF.add("psar");
		METRICS_RF.add("cci40");
		METRICS_RF.add("cci60");
		METRICS_RF.add("atr10"); 
		METRICS_RF.add("atr20");
		METRICS_RF.add("atr40"); 
		METRICS_RF.add("atr60"); 
		METRICS_RF.add("mvol10"); 
		METRICS_RF.add("mvol20"); 
		METRICS_RF.add("mvol50"); 
		METRICS_RF.add("mvol100"); 
		METRICS_RF.add("mvol200"); 
		
		// METRICS_NB uses hour but not close - These seem to be low info gain
		METRICS_NB.add("rsi2");
		METRICS_NB.add("rsi5"); 
		METRICS_NB.add("mfi4"); 
		METRICS_NB.add("mfi8"); 
		METRICS_NB.add("mfi12"); 
		METRICS_NB.add("mfi16");
		METRICS_NB.add("consecutiveups"); 
		METRICS_NB.add("consecutivedowns"); 
		METRICS_NB.add("pricebolls10");
		METRICS_NB.add("pricebolls20");
		METRICS_NB.add("intradayboll10");
		METRICS_NB.add("intradayboll20");
		METRICS_NB.add("intradayboll50");
		METRICS_NB.add("volumebolls10"); 
		METRICS_NB.add("volumebolls20");
		METRICS_NB.add("breakout200");
		METRICS_NB.add("williamsr10");
		METRICS_NB.add("williamsr20"); 
		METRICS_NB.add("ultimateoscillator4_10_25"); 
		METRICS_NB.add("ultimateoscillator8_20_50");
		METRICS_NB.add("aroonoscillator10"); 
		METRICS_NB.add("aroonoscillator25");
		METRICS_NB.add("aroonoscillator50"); 
		METRICS_NB.add("stochasticdrsi9_2_2");
		METRICS_NB.add("stochasticdrsi14_3_3"); 
		METRICS_NB.add("stochasticdrsi20_5_5"); 
		METRICS_NB.add("stochastick9_2_2");
		METRICS_NB.add("stochasticd9_2_2");
		METRICS_NB.add("stochastick14_3_3");
		METRICS_NB.add("stochasticd14_3_3"); 
		METRICS_NB.add("stochastick20_5_5");
		METRICS_NB.add("stochasticd20_5_5"); 
		METRICS_NB.add("cci5");
		METRICS_NB.add("cci10");
		METRICS_NB.add("cci20"); 
		
		METRICS.addAll(METRICS_NB);
//		METRICS.addAll(METRICS_RF);
		
		// METRIC_NEEDED_BARS
		METRIC_NEEDED_BARS.put("rsi2", 7);
		METRIC_NEEDED_BARS.put("rsi5", 10);
		METRIC_NEEDED_BARS.put("rsi10", 15);
		METRIC_NEEDED_BARS.put("rsi14", 19);
		METRIC_NEEDED_BARS.put("rsi25", 30);
		METRIC_NEEDED_BARS.put("rsi40", 45);
		METRIC_NEEDED_BARS.put("mfi4", 9);
		METRIC_NEEDED_BARS.put("mfi8", 12);
		METRIC_NEEDED_BARS.put("mfi12", 17);
		METRIC_NEEDED_BARS.put("mfi16", 21);
		METRIC_NEEDED_BARS.put("mfi30", 35);
		METRIC_NEEDED_BARS.put("mfi60", 65);
		METRIC_NEEDED_BARS.put("consecutiveups", 20);
		METRIC_NEEDED_BARS.put("consecutivedowns", 20);
		METRIC_NEEDED_BARS.put("cps", 20);
		METRIC_NEEDED_BARS.put("pricebolls10", 15);
		METRIC_NEEDED_BARS.put("pricebolls20", 25);
		METRIC_NEEDED_BARS.put("pricebolls50", 55);
		METRIC_NEEDED_BARS.put("pricebolls100", 105);
		METRIC_NEEDED_BARS.put("pricebolls200", 205);
		METRIC_NEEDED_BARS.put("gapboll10", 15);
		METRIC_NEEDED_BARS.put("gapboll20", 25);
		METRIC_NEEDED_BARS.put("gapboll50", 55);
		METRIC_NEEDED_BARS.put("intradayboll10", 15);
		METRIC_NEEDED_BARS.put("intradayboll20", 25);
		METRIC_NEEDED_BARS.put("intradayboll50", 55);
		METRIC_NEEDED_BARS.put("volumebolls10", 15);
		METRIC_NEEDED_BARS.put("volumebolls20", 25);
		METRIC_NEEDED_BARS.put("volumebolls50", 55);
		METRIC_NEEDED_BARS.put("volumebolls100", 105);
		METRIC_NEEDED_BARS.put("volumebolls200", 205);
		METRIC_NEEDED_BARS.put("dvol5ema", 50);
		METRIC_NEEDED_BARS.put("dvol10ema", 30);
		METRIC_NEEDED_BARS.put("dvol25ema", 20);
		METRIC_NEEDED_BARS.put("dvol50ema", 10);
		METRIC_NEEDED_BARS.put("dvol75ema", 10);
		METRIC_NEEDED_BARS.put("breakout20", 25);
		METRIC_NEEDED_BARS.put("breakout50", 55);
		METRIC_NEEDED_BARS.put("breakout100", 105);
		METRIC_NEEDED_BARS.put("breakout200", 205);
		METRIC_NEEDED_BARS.put("williamsr10", 15);
		METRIC_NEEDED_BARS.put("williamsr20", 25);
		METRIC_NEEDED_BARS.put("williamsr50", 55);
		METRIC_NEEDED_BARS.put("macd6_13_5", 18);
		METRIC_NEEDED_BARS.put("macd12_26_9", 31);
		METRIC_NEEDED_BARS.put("macd20_40_9", 45);
		METRIC_NEEDED_BARS.put("macdsignal6_13_5", 18);
		METRIC_NEEDED_BARS.put("macdsignal12_26_9", 31);
		METRIC_NEEDED_BARS.put("macdsignal20_40_9", 45);
		METRIC_NEEDED_BARS.put("macdhistory6_13_4", 18);
		METRIC_NEEDED_BARS.put("macdhistory12_26_9", 31);
		METRIC_NEEDED_BARS.put("macdhistory20_40_9", 45);
		METRIC_NEEDED_BARS.put("tsf10", 15);
		METRIC_NEEDED_BARS.put("tsf20", 25);
		METRIC_NEEDED_BARS.put("tsf30", 35);
		METRIC_NEEDED_BARS.put("tsf40", 45);
		METRIC_NEEDED_BARS.put("tsf60", 65);
		METRIC_NEEDED_BARS.put("psar", 20);
		METRIC_NEEDED_BARS.put("ultimateoscillator4_10_25", 30);
		METRIC_NEEDED_BARS.put("ultimateoscillator8_20_50", 55);
		METRIC_NEEDED_BARS.put("ultimateoscillator16_40_100", 105);
		METRIC_NEEDED_BARS.put("aroonoscillator10", 15);
		METRIC_NEEDED_BARS.put("aroonoscillator25", 30);
		METRIC_NEEDED_BARS.put("aroonoscillator50", 55);
		METRIC_NEEDED_BARS.put("stochasticdrsi9_2_2", 11);
		METRIC_NEEDED_BARS.put("stochasticdrsi14_3_3", 19);
		METRIC_NEEDED_BARS.put("stochasticdrsi20_5_5", 25);
		METRIC_NEEDED_BARS.put("stochastick9_2_2", 11);
		METRIC_NEEDED_BARS.put("stochasticd9_2_2", 11);
		METRIC_NEEDED_BARS.put("stochastick14_3_3", 19);
		METRIC_NEEDED_BARS.put("stochasticd14_3_3", 19);
		METRIC_NEEDED_BARS.put("stochastick20_5_5", 25);
		METRIC_NEEDED_BARS.put("stochasticd20_5_5", 25);
		METRIC_NEEDED_BARS.put("cci5", 10);
		METRIC_NEEDED_BARS.put("cci10", 15);
		METRIC_NEEDED_BARS.put("cci20", 25);
		METRIC_NEEDED_BARS.put("cci40", 45);
		METRIC_NEEDED_BARS.put("cci60", 65);
		METRIC_NEEDED_BARS.put("atr10", 15);
		METRIC_NEEDED_BARS.put("atr20", 25);
		METRIC_NEEDED_BARS.put("atr40", 45);
		METRIC_NEEDED_BARS.put("atr60", 65);
		METRIC_NEEDED_BARS.put("mvol10", 15);
		METRIC_NEEDED_BARS.put("mvol20", 25);
		METRIC_NEEDED_BARS.put("mvol50", 55);
		METRIC_NEEDED_BARS.put("mvol100", 105);
		METRIC_NEEDED_BARS.put("mvol200", 205);
		METRIC_NEEDED_BARS.put("timerange.05", 200);
		METRIC_NEEDED_BARS.put("timerange.1", 400);
		METRIC_NEEDED_BARS.put("timerange.2", 600);
		METRIC_NEEDED_BARS.put("timerange.3", 800);
		METRIC_NEEDED_BARS.put("timerange.5", 1000);
		METRIC_NEEDED_BARS.put("rangepressure50", 55);
		METRIC_NEEDED_BARS.put("rangepressure100", 105);
		METRIC_NEEDED_BARS.put("rangepressure200", 205);
//		METRIC_NEEDED_BARS.put("cdlhammer", 10);
//		METRIC_NEEDED_BARS.put("cdldoji", 10);
//		METRIC_NEEDED_BARS.put("cdlmorningstar", 10);
		
		// OTHER_SELL_METRICS
		OTHER_SELL_METRICS.add(OTHER_SELL_METRIC_NUM_BARS_LATER);
		OTHER_SELL_METRICS.add(OTHER_SELL_METRIC_PERCENT_UP);
		OTHER_SELL_METRICS.add(OTHER_SELL_METRIC_PERCENT_DOWN);
		
		// STOP_METRICS
		STOP_METRICS.add(STOP_METRIC_NONE);
		STOP_METRICS.add(STOP_METRIC_PERCENT_DOWN);
		STOP_METRICS.add(STOP_METRIC_PERCENT_UP);
		STOP_METRICS.add(STOP_METRIC_NUM_BARS);
	}
}